<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-18 14:15

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.2.8 on 2025-11-24 19:04

>>>>>>> 4a170673d304f27ec1b68ed533789605de69eeae
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 4a170673d304f27ec1b68ed533789605de69eeae
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
=======
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_de_consulta', models.CharField(db_column='TIPO_DE_CONSULTA', max_length=45)),
                ('retorno_agendado', models.DateField(db_column='RETORNO_AGENDADO')),
                ('tratamento', models.CharField(db_column='TRATAMENTO', max_length=45)),
                ('data_consulta', models.DateField(db_column='DATA_CONSULTA')),
                ('horario_consulta', models.TimeField(db_column='HORARIO_CONSULTA')),
                ('observacoes', models.CharField(db_column='OBSERVACOES', max_length=45)),
            ],
            options={
                'db_table': 'consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id_conta', models.IntegerField(db_column='ID_Conta', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_column='Usuario', max_length=20)),
                ('perfil', models.IntegerField(db_column='Perfil')),
            ],
            options={
                'db_table': 'conta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstoqueProduto',
            fields=[
                ('id_estoque_produto', models.AutoField(db_column='ID_Estoque_Produto', primary_key=True, serialize=False)),
                ('funcionario_id_funcionario', models.IntegerField(db_column='Funcionario_ID_Funcionario')),
                ('funcionario_perfil_id_perfil', models.IntegerField(db_column='Funcionario_Perfil_ID_Perfil')),
            ],
            options={
                'db_table': 'estoque_produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('feedback_app', models.CharField(db_column='FEEDBACK_APP', max_length=45)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackPet',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('feedback_pet', models.CharField(blank=True, db_column='FEEDBACK_PET', max_length=45, null=True)),
            ],
            options={
                'db_table': 'feedback_pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(db_column='ID_Funcionario', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=50)),
                ('cpf', models.IntegerField(db_column='CPF')),
                ('endereco', models.CharField(db_column='Endereco', max_length=60)),
                ('perfil_id_perfil', models.IntegerField(db_column='Perfil_ID_Perfil')),
            ],
            options={
                'db_table': 'funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.IntegerField(db_column='ID_Perfil', primary_key=True, serialize=False)),
                ('nome_perfil', models.CharField(db_column='Nome_Perfil', max_length=30)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('cpf', models.CharField(db_column='CPF', max_length=11, unique=True)),
                ('data_nascimento', models.DateField(db_column='DATA_NASCIMENTO')),
                ('genero', models.CharField(db_column='GENERO', max_length=45)),
            ],
            options={
                'db_table': 'pessoa fisica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=14, unique=True)),
                ('nome_fantasia', models.CharField(db_column='NOME_FANTASIA', max_length=45)),
                ('endereco', models.CharField(db_column='ENDERECO', max_length=45)),
                ('data_criacao', models.DateField(db_column='DATA_CRIACAO')),
            ],
            options={
                'db_table': 'pessoa juridica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=45)),
                ('data_nascimento', models.DateField(db_column='DATA_NASCIMENTO')),
                ('especie', models.CharField(db_column='ESPECIE', max_length=45)),
                ('raca', models.CharField(db_column='RAÇA', max_length=45)),
                ('sexo', models.CharField(db_column='SEXO', max_length=5)),
                ('pelagem', models.CharField(db_column='PELAGEM', max_length=45)),
                ('castrado', models.CharField(db_column='CASTRADO', max_length=3)),
            ],
            options={
                'db_table': 'pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(db_column='ID_Produto', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('validade', models.DateField(db_column='Validade')),
                ('fabricacao', models.DateField(db_column='Fabricacao')),
            ],
            options={
                'db_table': 'produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProntuarioPet',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('historico_veterinario', models.CharField(db_column='HISTORICO_VETERINARIO', max_length=150, unique=True)),
                ('motivo_consulta', models.CharField(db_column='MOTIVO_CONSULTA', max_length=60)),
                ('avaliacao_geral', models.CharField(db_column='AVALIACAO_GERAL', max_length=150)),
                ('procedimentos', models.CharField(db_column='PROCEDIMENTOS', max_length=150)),
                ('diagnostico_conslusivo', models.CharField(db_column='DIAGNOSTICO_CONSLUSIVO', max_length=150)),
                ('observacao', models.CharField(db_column='OBSERVACAO', max_length=150)),
            ],
            options={
                'db_table': 'prontuario_pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('funcionario_id_funcionario', models.IntegerField(db_column='Funcionario_ID_Funcionario', primary_key=True, serialize=False)),
                ('funcionario_perfil_id_perfil', models.IntegerField(db_column='Funcionario_Perfil_ID_Perfil')),
                ('conta_id_conta', models.IntegerField(db_column='Conta_ID_Conta')),
                ('conta_perfil_id_perfil', models.IntegerField(db_column='Conta_Perfil_ID_Perfil')),
            ],
            options={
                'db_table': 'registro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_tutor', models.CharField(db_column='NOME_TUTOR', max_length=45)),
                ('cpf', models.CharField(db_column='CPF', max_length=11, unique=True)),
                ('email', models.CharField(db_column='EMAIL', max_length=45)),
                ('endereco', models.CharField(db_column='ENDEREÇO', max_length=60)),
                ('data_de_nascimento', models.DateField(db_column='DATA DE NASCIMENTO')),
                ('senha_tutor', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'tutor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(db_column='ID_Venda', primary_key=True, serialize=False)),
                ('dia', models.DateField(db_column='Dia')),
                ('hora', models.TimeField(db_column='Hora')),
                ('valor', models.FloatField(db_column='Valor')),
                ('funcionario_id_funcionario', models.IntegerField(db_column='Funcionario_ID_Funcionario')),
            ],
            options={
                'db_table': 'venda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendaHasProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'venda_has_produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=45)),
                ('email', models.CharField(db_column='EMAIL', max_length=45)),
                ('crmv', models.IntegerField(db_column='CRMV', unique=True)),
                ('uf_crmv', models.CharField(db_column='UF_CRMV', max_length=5)),
                ('telefone', models.CharField(db_column='TELEFONE', max_length=11)),
                ('tipo_veterinario', models.CharField(db_column='TIPO_VETERINARIO', max_length=8)),
            ],
            options={
                'db_table': 'veterinario',
                'managed': False,
            },
>>>>>>> 4a170673d304f27ec1b68ed533789605de69eeae
        ),
    ]
