# Generated by Django 5.2.8 on 2025-11-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'managed': True},
        ),
    ]
